# Site settings
title: Kaunas JS
email: kaunasjs@gmail.com
description: > # none
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaunasjs.lt" # the base hostname & protocol for your site
twitter_username: kaunasjs
github_username:  kaunasjs

# Build settings
markdown: kramdown
