# Site settings
title: Kaunas JS
email: kaunasjs@gmail.com
description: > #
  Norim suburti JavaScript programuojančius žmones Kaune. Susitikim
  kartą į mėnesį pasidalinti žiniom ir įspūdžiais.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaunasjs.lt" # the base hostname & protocol for your site
twitter_username: kaunasjs
github_username:  kaunasjs

# Publish posts with a future date
future: true

# Build settings
markdown: kramdown
